[project]
name = "agentic-ai-em-to-fde-journey"
version = "0.1.0"
description = "getting started with llm and python hello world"
readme = "README.md"
authors = [
    { email = "ziad.sv@outlook.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mcp<2",
    "numpy>=2.0.2",
    "openai>=2.48.0",
    "pgvector>=0.4.2",
    "psycopg[binary]>=3.2.13",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.1",
    "sentence-transformers>=5.1.2",
]

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
